CREATE DATABASE Hopefund;

CREATE TABLE Hopefund.Users(
	UserId NUMBER(1,0) NOT NULL AUTO_INCREMENT,
	UserName VARCHAR2(255) NOT NULL,
	UserPwd VARCHAR2(40) NOT NULL,
	PRIMARY KEY (UserId));
	
CREATE TABLE Hopefund.Events(
	EventId NUMBER(1,0) NOT NULL AUTO_INCREMENT,
	EventName VARCHAR2(255) NOT NULL,
	EventDescription VARCHAR2(255) NOT NULL,
	PRIMARY KEY (EventName));
	
CREATE TABLE Hopefund.Reports(
	ReportId NUMBER(1,0) NOT NULL AUTO_INCREMENT,
	ReportName VARCHAR2(255) NOT NULL,
	ReportDescription VARCHAR2(255) NOT NULL,
	PRIMARY KEY (ReportId));